// Concatenates the engine's ES modules (src/*) into ONE readable, editable
// TypeScript file: dist/naiowod.ts. This is NOT a bundle - nothing is minified
// or transpiled. Inter-module import/export *wiring* is stripped (a NovelAI
// script runs in one global scope, so cross-file imports are neither needed nor
// allowed), but every declaration keeps its original source text. The result
// reads like the modules laid end to end.
//
// `bun run build` regenerates it; test/build.test.ts fails the suite if the
// committed dist/naiowod.ts ever drifts from src/, so the single file stays in
// sync with the modules on every change. To use it, paste the TypeScript below
// into NovelAI's script editor - no metadata header needed. (The `.naiscript`
// YAML frontmatter is only for exporting/importing scripts, which embeds a
// script id; pasting plain TypeScript does not need it.)

// Modules in dependency order: each references only names declared above it.
// (host -> core -> rules -> command -> services -> state -> game ->
//  window -> index/init -> main/bootstrap.)
export const MODULES = [
  "src/host.ts",
  "src/core/traits.ts",
  "src/core/cardtext.ts",
  "src/core/expr.ts",
  "src/core/dice.ts",
  "src/core/damage.ts",
  "src/core/time.ts",
  "src/core/bus.ts",
  "src/wizard.ts",
  "src/rolls.ts",
  "src/rules.ts",
  "src/command.ts",
  "src/services.ts",
  "src/state.ts",
  // ORDER MEASURED, NOT ASSUMED - see below. These are src/game.ts's former
  // contents; the list is regenerated by scripts/game-order.ts.
  "src/game/common.ts",
  "src/game/effects.ts",
  "src/game/character.ts",
  "src/game/places.ts",
  "src/game/contests.ts",
  "src/game/time.ts",
  "src/game/narration.ts",
  "src/game/powers.ts",
  "src/game/afflictions.ts",
  "src/game/show.ts",
  "src/game/context.ts",
  "src/game.ts",
  "src/ui-text.ts",
  "src/window.ts",
  "src/index.ts",
  "src/main.ts",
] as const;

const ROOT = new URL("../", import.meta.url);
export const OUTPUT_PATH = new URL("dist/naiowod.ts", ROOT).pathname;

// Strip a module's inter-file wiring, leaving stand-alone declarations. Order
// matters: remove whole re-export / import statements first, THEN the leading
// `export ` keyword from the declarations that remain.
export function stripModule(src: string): string {
  return src
    // whole-line re-exports: `export * from "./x";`
    .replace(/^export\s+\*\s+from\s*['"][^'"]+['"];?[ \t]*\r?\n/gm, "")
    // whole-statement re-exports: `export { A, B } from "./x";` (single/multi-line),
    // and the TYPE-ONLY form. `export type { T } from "./x";` used to fall past
    // here and then lose only its `export `, emitting `type { T } from "./x";` -
    // which is not valid TypeScript, and which the leaked-wiring guard below
    // could not see because that line begins with neither import nor export.
    // The standalone type-check of the artifact is what caught it.
    .replace(/^export\s+type\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"];?[ \t]*\r?\n/gm, "")
    .replace(/^export\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"];?[ \t]*\r?\n/gm, "")
    // import statements, single- or multi-line: `import … from "./x";`
    .replace(/^import\b[\s\S]*?from\s*['"][^'"]+['"];?[ \t]*\r?\n/gm, "")
    // leading `export ` on the surviving declarations (const/class/interface/…)
    .replace(/^export[ \t]+/gm, "")
    .trim();
}

export async function buildSingleFile(): Promise<string> {
  const header = [
    "// NAIoWoD - World of Darkness (Dark Ages) engine for NovelAI scripting.",
    "// GENERATED - do not edit by hand. This is src/* concatenated in dependency",
    "// order with inter-module import/export wiring removed; every declaration",
    "// keeps its original source. Edit the modules under src/, then `bun run build`.",
    "// test/build.test.ts fails if this file drifts from src/.",
    "//",
    "// This is the RELEASE artifact. It defines NO NovelAI types and no `api`:",
    "// the host injects the global `api` and all its types at runtime. The type",
    "// declarations are NovelAI's own, vendored at types/novelai/script-types.d.ts",
    "// (the off-host mock in src/host-mock.ts is NOT included here).",
    "//",
    "// Paste this TypeScript into NovelAI's script editor as-is - no header needed.",
    "//",
    "// Order: host -> core/traits -> core/dice -> core/damage -> core/time ->",
    "//        wizard -> rolls -> rules -> command -> services -> state ->",
    "//        game -> window -> init (index.ts) -> bootstrap (main.ts)",
  ].join("\n");

  const sections = [header];
  for (const rel of MODULES) {
    const body = stripModule(await Bun.file(new URL(rel, ROOT)).text());
    sections.push(`//#region ${rel}\n${body}\n//#endregion ${rel}`);
  }
  return sections.join("\n\n") + "\n";
}

if (import.meta.main) {
  const out = await buildSingleFile();

  // Guardrails: starts with the generated comment (NOT naiscript frontmatter),
  // and no inter-module wiring survived (no line may start with import/export).
  if (!out.startsWith("//")) throw new Error("generated header comment missing");
  if (out.startsWith("/*---")) throw new Error("naiscript frontmatter should not be emitted");
  // `type {` and `from "` catch the re-export forms that survive with their
  // leading keyword removed - the shape that shipped a broken artifact once.
  const leaked = out.split("\n").filter((l) =>
    /^(import|export)\b/.test(l) || /^type\s*\{/.test(l) || /^\s*\}\s*from\s*['"]/.test(l));
  if (leaked.length) {
    throw new Error(`inter-module wiring leaked:\n  ${leaked.slice(0, 5).join("\n  ")}`);
  }

  await Bun.write(OUTPUT_PATH, out);
  console.log(`dist/naiowod.ts written (${(out.length / 1024).toFixed(1)} KB)`);
}
